server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
rbac:
  enable: true  #启动rbac-spring-boot-starter组件
  tokenExpireTime: 7200  #无操作2小时过期
  tokenName: authorization  #request header中token的变量名
  redisKeyPrefix: 'rbac:'
spring:
  redis:
    host: pi
    port: 16379
    password:
    timeout: 5000
    jedis: # 或lettuce
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pi:3306/rbac_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: vayne
    password:
    hikari:
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
logging:
  level:
    com:
      github:
        flashvayne:
          rbac:
            mapper: debug
          demo:
            mapper: debug
    org:
      zalando:
        logbook: trace
logbook:
  filter:
    form-request-mode: off
  format:
    style: http